---
# Copyright (c) 2021 Mohamed Tawfik <m_tawfik@aucegypt.edu>

- name: Ensure that syncoid SSH identities are present
  ansible.builtin.user:
    name: 'root'
    generate_ssh_key: True
    ssh_key_file:    '.ssh/{{ item.name }}'
    ssh_key_type:    '{{ item.type    | d(syncoid__ssh_key_type) }}'
    ssh_key_bits:    '{{ item.bits    | d(syncoid__ssh_key_bits) }}'
    ssh_key_comment: '{{ item.comment | d(syncoid__ssh_key_comment) }}'
  with_items: '{{ q("flattened",
                    [ syncoid__ssh_default_identity ]
                    + syncoid__ssh_identities) }}'
  notify: [ 'Refresh host facts' ]
  when: item.name|d() and item.state|d('present') not in [ 'absent', 'ignore' ]

- name: Make sure /root/.ssh/known_hosts file exists
  ansible.builtin.command:
    cmd: touch /root/.ssh/known_hosts
    creates: '/root/.ssh/known_hosts'
